# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# development:
#   adapter: sqlite3
#   database: db/development.sqlite3

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['PG_DATABASE_URL'] %>
  # url: postgres://advoc:advoc@localhost:5434/advoc
  

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: <%= ENV['DATABASE_NAME'] %>
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: <%= ENV['DATABASE_USERNAME'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   host: <%= ENV['DATABASE_HOST'] %>
#   port: <%= ENV.fetch('DATABASE_PORT', '5432') %>

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['PG_DATABASE_URL'] %>